"""empty message

Revision ID: 392ce4a4d742
Revises: d7f79f860c24
Create Date: 2024-08-06 03:29:40.440422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392ce4a4d742'
down_revision = 'd7f79f860c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=10), nullable=False))
        batch_op.drop_column('user_name')
        batch_op.drop_column('sur_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sur_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('username')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
